### PR TITLE
Fixes issue serializing DataCite for records without an award number

### LINKED ISSUE #1360: Error generating datacite XML for record
Honeybadger logged the following exception:

```
Backtrace

    line 230 of [PROJECT_ROOT]/app/models/pdc_serialization/datacite.rb: new
    line 230 of [PROJECT_ROOT]/app/models/pdc_serialization/datacite.rb: block in funding_references_from_work_resource
    line 229 of [PROJECT_ROOT]/app/models/pdc_serialization/datacite.rb: map

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/99214/faults/97747017)
```

You can replicate this error by trying to view the DataCite version of the record in production: https://pdc-describe-prod.princeton.edu/describe/works/40

(this probably also explains why the datacite.xml was not generated in issue https://github.com/pulibrary/pdc_describe/issues/1349)

### PR DESCRIPTION
**Pull request by hectorcorrea**
Closes #1360

### CODE REVIEW

File: app/models/pdc_serialization/datacite.rb [hunk 1]
```diff
@@ -224,15 +224,15 @@ def rights_from_work_resource(resource)
...
-              ::Datacite::Mapping::FundingReference.new(name: funder.funder_name, award_number: award)
-            end
+            award = if funder.award_number.present?
+                      ::Datacite::Mapping::AwardNumber.new(uri: funder.award_uri, value: funder.award_number)
+                    end
+            funder_identifier = if funder.ror.present?
+                                  ::Datacite::Mapping::FunderIdentifier.new(type: type_ror, value: funder.ror)
+                                end
+            ::Datacite::Mapping::FundingReference.new(name: funder.funder_name, award_number: award, identifier: funder_identifier)
           end
```
Comment (hectorcorrea) [inline app/models/pdc_serialization/datacite.rb:236]: The new logic only uses the award information for DataCite serialization if there is a award number indicated.

**Review by jrgriffiniii — APPROVED** [review]
