### PR TITLE
Handles external user ids

### LINKED ISSUE #993: Dashboard for Princeton guest accounts
The dashboard page is broken for Princeton guest accounts. Users get a generic error page when accessing `https://pdc-describe-staging.princeton.edu/describe/users/guest-user@gmail.com`. 

The log file shows the following: 
```
ActiveRecord::RecordNotFound (can't find record with friendly id: "guest-user@gmail")
```

The user can navigate to the Works list page `https://pdc-describe-staging.princeton.edu/describe/works` and select a work from there.

### PR DESCRIPTION
**Pull request by hectorcorrea**
Fixes the problem with the redirect for external net id used in guest accounts (e.g. sometest@gmail.com)

Fixes #993

### CODE REVIEW

File: app/controllers/users_controller.rb [hunk 1]
```diff
@@ -53,8 +53,21 @@ def update
...
+      @user = User.friendly.find(user_id)
+      redirect_to action: action_name, id: @user.friendly_id, status: :moved_permanently unless @user.friendly_id == user_id
+    end
+
+    def user_id_from_url
+      # For external users UID is in the form `user-name@gmail.com`, however, Rails eats the ".com" from
+      # the UID and dumps it into the `format` param. Here we make sure the ".com" is preserved when the
+      # UID looks to be an external user id.
+      external_uid = params[:id].include?("@")
+      if external_uid && params["format"] == "com"
```
Comment (hectorcorrea) [inline app/controllers/users_controller.rb:66]: We could make this more generic but I wanted to do something quick to get it on staging for user testing with the existing account to continue.

**Review by jrgriffiniii — APPROVED** [review]
