### PR TITLE
Fixes the bad provenance logged when deleting files

### LINKED ISSUE #1834: File provenance when deleting files
When I delete a file the provenance register two records for the delete. One correctly assigned to the user that delete the file and one indicating "unknown user. The system should not log the "unknown user" provenance in this case since we know the user that deleted the file:

Screenshot 2024-06-04 at 11 59 23 AM

This is related to issue #1833 but not the same.

Look at the snapshots and figure out why the snapshot after the delete (if it is created) is not the same as the snapshot when you come back.

### PR DESCRIPTION
**Pull request by hectorcorrea**
Logs the correct provenance (who deleted the file) when deleting a file via the Edit screen:

Screenshot 2024-06-24 at 4 23 31 PM

Closes #1834

### CODE REVIEW

File: app/services/work_uploads_edit_service.rb [hunk 1]
```diff
@@ -11,9 +11,12 @@ def initialize(work, current_user)
...
     delete_uploads(deleted_files)
     add_uploads(added_files)
-    if work.changes.count > 0
+    file_list_changed = deleted_files.count > 0 || added_files.count > 0
+    if file_list_changed
       s3_service.client_s3_files(reload: true)
-      work.reload # reload the work to pick up the changes in the attachments
+      # Pick up the changes in the attachments and assings them to the current user
+      work.reload
+      work.reload_snapshots(user_id: current_user.id)
```
Comment (hectorcorrea) [inline app/services/work_uploads_edit_service.rb:19]: This is the big change on this PR: I am forcing to reload the snapshots so that the changes are assigned to the current user.

File: app/services/work_uploads_edit_service.rb [hunk 2]
```diff
@@ -45,9 +48,7 @@ def delete_uploads(deleted_files)
 
       deleted_files.each do |filename|
         s3_service.delete_s3_object(filename)
-        work.track_change(:removed, filename)
       end
-      work.log_file_changes(@current_user.id)
```
Comment (hectorcorrea) [inline app/services/work_uploads_edit_service.rb:50]: The extra logs are not needed since the `work.reload` logs the changes.

**Review by leefaisonr — APPROVED** [review]
LGTM - Thanks!
