### PR TITLE
Fixes bug fetching user's own works

### LINKED ISSUE #389: When I administer a collection I can not see works in other collections on my dashboard
As a collection administrator, and a depositor I would like to see my works AND other people's works on my dashboard.

If the works that I submitted are in a collection I do not administer, they disappear from my dashboard.

I currently have 10 works locally, 9 of which are unfinished:
```
[27] pry(main)> Work.unfinished_works(me).count
=> 9
[28] pry(main)> me.add_role("collection_admin", Collection.find(4))
[29] pry(main)> Work.unfinished_works(me).count
=> 2
```

### PR DESCRIPTION
**Pull request by carolyncole**
Fixes bug in code to fetch works by state to always include the user own works (even if they are an administrator)

Big thanks to @carolyncole for providing the initial test that surfaced the bug.

Fixes #389

### CODE REVIEW

File: app/models/work.rb [hunk 1]
```diff
@@ -116,10 +116,11 @@ def publish_test_doi?
 
       def works_by_user_state(user, state)
         works = []
-        if user.admin_collections.count == 0
-          # Just the user's own works by state
-          works += Work.where(created_by_user_id: user, state: state)
-        else
+
+        # The user's own works by state (if any)
+        works += Work.where(created_by_user_id: user, state: state)
```
Comment (carolyncole) [inline app/models/work.rb:121]: Instead of a `+=` here, could you combine line. 118 and 121 (Since it is now happening every time)
```suggestion
        works = Work.where(created_by_user_id: user, state: state)
```

**Review by carolyncole — COMMENTED** [review]
@hectorcorrea Since I created this PR, I can not approve or request changes, but I can comment.

Other than the requested change it looks good to me...

File: app/models/work.rb (hunk 1 above)
Comment (hectorcorrea) [reply app/models/work.rb:121]: Funny. I tried that first, but turns out `Work.where` returns an `ActiveRelation` that looks like an array but it is not an array. Since it is not an array the code blows up a few lines down when it does `works << work unless already_included`. I could probably come up with a clever way to handle this but I thought the simplest and cleanest was to use a plain array and append to it.

Comment (carolyncole) [reply app/models/work.rb:121]: Oh!  You just need a `to_a` on the end of the query.

**Review by bess — APPROVED** [review]
