### PR TITLE
Use Base64 encoded MD5 checksum as required by updated AWS S3 API

### LINKED ISSUE #1273: Data migration bug: The Content-MD5 you specified was invalid
Automated data migration is broken. When you push the button it gives the attached error, but no error is raised to Honeybadger. 

Screenshot 2023-06-20 at 2 00 10 PM

### PR DESCRIPTION
**Pull request by bess**
Fixes #1273 

Co-authored-by: Carolyn Cole <carolyncole@users.noreply.github.com>

### CODE REVIEW

File: app/services/pul_dspace_connector.rb [hunk 1]
```diff
@@ -87,9 +87,14 @@ def download_file(url, filename)
...
 
+    # rubocop:disable Metrics/MethodLength
     def checksum_file(filename, bitstream)
       checksum_class = Digest.const_get(bitstream["checkSum"]["checkSumAlgorithm"])
-      if checksum_class.file(filename).hexdigest != bitstream["checkSum"]["value"]
+      checksum = checksum_class.file(filename)
+      hexdigest = checksum.hexdigest
+      base64 = checksum.base64digest
+      bitstream["checkSum"]["base64"] = base64
+      if hexdigest != bitstream["checkSum"]["value"]
```
Comment (hectorcorrea) [inline app/services/pul_dspace_connector.rb:97]: Just double-checking that this was indeed meant to be `value` and not `base64`

Comment (bess) [reply app/services/pul_dspace_connector.rb:97]: @hectorcorrea Yes, that's correct as-is. DSpace needs the hexdigest and S3 needs the base64digest.
