### PR TITLE
Fixes display issue when deleting a file

### LINKED ISSUE #1833: File name display when delete is clicked more than once
When I click on the "Delete File" link the file name is strike through but the system also displays a "#" symbol before the name and it should not:

Screenshot 2024-06-04 at 11 54 50 AM

If I then click "Undo delete" the file will keep the "#" before the name (it should not)

Screenshot 2024-06-04 at 11 54 57 AM

If I then click "Delete file" again, a new "#" symbol will be prefixed to the name:

Screenshot 2024-06-04 at 11 55 05 AM

### LINKED ISSUE #1835: Delete provenance count is wrong
If I click "Delete file" and then hit "cancel"

Screenshot 2024-06-04 at 12 03 30 PM

and then Edit the record again and click "Delete file" the display is incorrect (this is documented in #1833)

Screenshot 2024-06-04 at 12 04 09 PM

If I click "Save" the file will be deleted but the provenance will log an incorrect count for the number of files deleted:

Screenshot 2024-06-04 at 12 04 33 PM

Make sure the count is correct when deleting a file even in this scenario.

### PR DESCRIPTION
**Pull request by hectorcorrea**
Fixes the display issue when deleting a file **and** the file count of deleted file too.

Screenshot 2024-06-06 at 11 35 53 AM

Screenshot 2024-06-06 at 11 50 11 AM

Closes #1833 
Closes #1835

Issue #1834 is not fixed with this PR. That will be handled separately.

### CODE REVIEW

File: spec/system/work_edit_spec.rb [hunk 1]
```diff
@@ -69,6 +62,19 @@
...
     end
 
+    it "allows users to cancel the delete of one of the uploads" do
+      allow(ActiveStorage::PurgeJob).to receive(:new).and_call_original
+      allow(fake_s3_service).to receive(:client_s3_files).and_return([contents1, contents2], [contents2])
+
+      expect(page).to have_link "us_covid_2019.csv"
+      click_on "delete-file-#{contents1.safe_id}"
+      expect(page).not_to have_link "us_covid_2019.csv"
+      expect(page.html.include?("<s> us_covid_2019.csv</s>")).to be true
```
Comment (hectorcorrea) [inline spec/system/work_edit_spec.rb:72]: This is the line that test that the extra `#` is not added to the text.

**Review by jrgriffiniii — APPROVED** [review]
