### PR TITLE
Handle GAP accounts logging in from CAS

### LINKED ISSUE #1901: ActiveRecord::NotNullViolation in users/omniauth_callbacks # cas
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "email" of relation "users" violates not-null constraint
DETAIL:  Failing row contains (329, null, , null, null, null, 2024-08-16 18:33:33.033377, 2024-08-16 18:33:33.033377, cas, abartelmann_gmail_com, null, 1, abartelmann@gmail.com, abartelmann@gmail.com, abartelmann@gmail.com, t).

## Backtrace

    line 52 of [PROJECT_ROOT]/app/models/user.rb: new_from_cas
    line 35 of [PROJECT_ROOT]/app/models/user.rb: from_cas
    line 5 of [PROJECT_ROOT]/app/controllers/users/omniauth_callbacks_controller.rb: cas

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/99214/faults/110500718)

### PR DESCRIPTION
**Pull request by hectorcorrea**
Closes #1901

### CODE REVIEW

File: app/models/user.rb [hunk 1]
```diff
@@ -58,12 +58,26 @@ def self.safe_uid(uid)
     uid.gsub(/[^(0-9a-zA-Z_\-)]/, "_")
   end
 
+  def self.email_from_access_token(access_token)
+    if !access_token.extra.mail.nil?
+      # For typical Princeton accounts the email comes on the `email` field
+      access_token.extra.mail
+    elsif User.looks_like_email_address?(access_token.extra.givenname)
+      # For Guest Access Accounts (GAP) the email comes in the `givenname`
```
Comment (jrgriffiniii) [inline app/models/user.rb:66]: 👍

File: spec/models/user_spec.rb [hunk 2]
```diff
@@ -81,6 +82,16 @@
         expect(user.uid).to eq "test_user_example_com"
       end
     end
+
+    context "GAP accounts" do
+      it "process GAP account correctly" do
+        # GAP accounts don't have the email on the email field,
```
Comment (jrgriffiniii) [inline spec/models/user_spec.rb:88]: 👍

**Review by jrgriffiniii — APPROVED** [review]
